<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LearnCsla.Dal\LearnCsla.Dal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Csla" Version="10.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.5" />
    <PackageReference Include="Csla.Generator.AutoImplementProperties.CSharp" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
